Articles/urls.py
from django.urls import path
from . import views
app_name = 'Articles'
urlpatterns = [
    path('', views.Articles, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug>/', views.article_detail, name="detail"),


]

Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from Articles import views as Articles_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about,),
    path('', Articles_views.Articles, name="home"),
    path('Articles/', include('Articles.urls')),
    path('accounts/', include('accounts.urls'))

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.signup, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

Articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):

    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    #author = models.ForeignKey(User, on_delete=models.CASCADE, )

    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + '...'

accounts/models.py
from django.db import models

# Create your models here.

Articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

Articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


def Articles(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'Articles/Articles.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'Articles/Article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('Articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'Articles/article_create.html', {'form': form})

Blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup(request, ):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('Articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('Articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'form':form})
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('Articles:list')

Articles/templates/Articles/Article_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="Article_detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

Articles/templates/Articles/Articles.html
{% extends 'base.html' %} {% block content %}
<h1>Your Place</h1>
<div class="articles">
    {% for article in articles %}

    <div class="article">

        <h2><a href="{% url 'Articles:detail' slug=article.slug %}">{{ article.title }}</a> </h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>

    </div>
    {% endfor %}
</div>
{% endblock %}

Articles/templates/Articles/article_create.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="create-article">
        <h2> Create an awesome new article</h2>
        <form class="site-form" action="{% url 'Articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="create">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        {% endif %}
            <input type="submit" value="login">
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}"> Sign Up</a> </p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About us</h1>
<p> we like django</p>
{% endblock %}

templates/base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Articles</title>
    <link rel="stylesheet" type='text/css' href="{% static 'style.css' %}" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhai+2&display=swap" rel="stylesheet">
</head>

<body>
    <nav class="navbar">
        <header class="wrapper">

            <h1>
                <a href="{% url 'home' %}"><img class="logo" src="{% static 'bhagya1.jpeg' %}" /></a>
            </h1>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'Articles:create' %}" class="highlight">New article</a> </li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
    </nav>

    </header>
    <div class="wrapper">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1> This is the Homepage</h1>
<p>welcome to my blog</p>

{% endblock %}